FROM BASE_IMAGE

RUN mkdir --parent /home/malware

RUN useradd -r --user-group -u 1002 -d /home/malware -s /sbin/nologin malware

WORKDIR /home/malware

COPY EXECUTABLE .

RUN chmod +x EXECUTABLE

USER malware

ENTRYPOINT ./EXECUTABLE